# Configuration for deploying to Netlify

# I'd prefer the redirects go at the bottom, since the list may grow massively in the future,
# but TOML's INI-style tables have to go at the end, since they have no end delimiter.

redirects = [
	{from = "/hour-glass-cursor.html", to = "/hour-glass-cursor/"},
	{from = "/hour-glass-arrow-cursor.html", to = "/hour-glass-arrow-cursor/"},
	{from = "/globe-downloading-cursor.html", to = "/globe-downloading-cursor/"},
	{from = "/hour-glass-cursor", to = "/hour-glass-cursor/"},
	{from = "/hour-glass-arrow-cursor", to = "/hour-glass-arrow-cursor/"},
	{from = "/globe-downloading-cursor", to = "/globe-downloading-cursor/"},
]

[build]
	publish = "out"
	command = "npm run build"
	GIT_LFS_ENABLED = true
	GIT_LFS_FETCH_INCLUDE = "*"
